### ISSUE TITLE
@Transactional是否支持webase回滚

### ISSUE THREAD

**Issue by zhangbincheng1997** [jiuyu-software/supply-chain-demo#6]
如题，如果MySQL异常，区块链相关操作是否支持回滚？

**Comment by freezehe** [comment]
目前不支持，调用第三方接口了，我采用的是http+json方式调用合约方法，后续我会考虑把区块链存储层替换为mysql，结合脚手架，到时候就同一个工程service之间调用，这个我觉得应该是支持了。

**Comment by zhangbincheng1997** [comment]
嗯，需要验证下，FISCO CRUD SDK是否支持@Transactional。
如果不支持，真不知道还有什么好方案了。:sob:

**Comment by freezehe** [comment]
后续会持续更新
