### ISSUE TITLE
创建新链时，合约交易失败，目前的合约是否存在问题？

### ISSUE THREAD

**Issue by polanwind** [jiuyu-software/supply-chain-demo#8]
![image](https://user-images.githubusercontent.com/26728169/141431546-991764cc-8eff-4619-a9e0-fc22cb31afb1.png)
上图是在webase管理平台内查询到的交易回执。经过查阅资料得知：

交易回滚，交易回执状态值为0x16，错误描述revert instruction，这个错误是因为合约的逻辑问题，包括:

* 访问调用未初始化的合约
* 访问初始化为0x0的合约
* 数组越界访问
* 除零错误
* 调用assert、revert
* 其他错误

想了解一下咱们这个平台内部的合约是否存在问题呢？目前是无法创建新链。报错为{"timestamp":"2021-11-12 15:25:12","status":500,"error":"Internal Server Error","message":"","path":"/supplychain/chain/new"}

**Comment by freezehe** [comment]
目前合约没有任何问题，我上次clone 下来实操了一下，请检测一下证书是否正确。
